### ISSUE TITLE
Category and Subscription Filter 

### ISSUE THREAD

**Issue by JaredRackley** [shanep-capstone/cs481-s21-team_4#16]
### User Story 
As a user, i want to be able to filter by category or by subscriptions so that I can find the content I want to view more easily.

### Tasks
- [ ] Display Filter button to User, which lets user filter by category or subscription
- [ ] When filter is chosen, db is queried for data matching the filter chosen
- [ ] Results of query are displayed to user

### Definition of Done
- Task 1, 2, 3: When user clicks on filter, and chooses a filter, only information matching the filter is selected and is then shown to the user in a consistent layout.
