### ISSUE TITLE
Register/Login Pages

### ISSUE THREAD

**Issue by JaredRackley** [shanep-capstone/cs481-s21-team_4#4]
### User Story
As a user I need to be able to register and login so that I can access audio streams.

### Tasks

- [ ]  User is able to register with an email and password.
- [ ]  User is able to set a profile picture.
- [ ]  Passwords have minimum requirements and are hashed to provide security.
- [ ]  User is able to login if registered with their credentials.
- [ ]  If user cannot login, there is a forgot password button that lets them reset their password.

### Definition of Done

- Task 1: User is able to be registered with an email and password. Email and password is put into db.
- Task 2: User is successfully able to add a profile picture. Picture is minimized then stored.
- Task 3: Password is not accepted unless minimum requirements are met. If user submits, form repopulates error data.
- Task 4: User is authenticated if login is successful.
- Task 5: A forgot password button lets the user reset their password via email or some other type of instructions.
